version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./keys:/app/keys
    container_name: oracle-vps-grabber
    restart: never
    environment:
      # Put your oracle cloud credentials here
      - OCI_USER =
      - OCI_FINGERPRINT =
      - OCI_TENANCY =
      - OCI_REGION =
      - OCI_KEY_FILE = ./keys/oracle_key.pem # DONT CHANGE THIS, EDIT THE FILE ON ./keys/oracle_key.pem TO CHANGE THE KEY

      # Optional discord webhook and user id to send a message when the script finishes
      - DISCORD_WEBHOOK = # The discord webhook to send the message to (optional, if not set, no message will be sent)
      - DISCORD_USER_ID = # The discord user to ping (optional, if not set, no one will be pinged)